version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "9001:8000"
    networks:
      - mynetwork
  app:
    build:
      context: ./app
    ports:
      - "9000:3000" 
    networks:
      - mynetwork

networks:
  mynetwork:
